### ISSUE TITLE
Login and Register Form Responsiveness

### ISSUE THREAD

**Issue by just-h** [szoszk/MensaMeet#47]
On small screens our login and registration forms aren't responsive since they have "min-width" in the css.
We should adjust the template files to use the "col-" classes to scale the width properly.

**To Reproduce**
1. Go to login/registration page
2. Set screen width less than 500px
3. See error

**Expected behavior**
Form centered and responsive on all widths.

**Comment by vesela-stefanova** [comment]
ill fix it for the next sprint
